Add unit tests, error/loading UI, FCM hardening, biometric step-up, and device fingerprint security

diff --git a/mobile/gradlew b/mobile/gradlew
--- a/mobile/gradlew
+++ b/mobile/gradlew
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 #
-# Copyright 2015 the original author or authors.
+# Copyright © 2015-2021 the original authors.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -22,76 +22,94 @@
 #
 #   Important for running:
 #
-#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
-#       not happen to be POSIX you'll need to install ksh or zsh and make sure it's
-#       in your PATH before /bin/sh
+#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
+#       noncompliant, but you have some other compliant shell such as ksh or
+#       bash, then to run this script, type that shell name before the whole
+#       command line, like:
 #
-#   (2) Avoid modifying this script unless you know what you are doing -- it's very
-#       easy to break Gradle if you mess with the variables the script uses.
+#           ksh Gradle
+#
+#       Busybox and similar reduced shells will NOT work, because this script
+#       requires all of these POSIX shell features:
+#         * functions;
+#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
+#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
+#         * compound commands having a testable exit status, especially «case»;
+#         * various built-in commands including «command», «set», and «ulimit».
+#
+#   Important for patching:
+#
+#   (2) This script targets any POSIX shell, so it avoids extensions provided
+#       by Bash, Ksh, etc; in particular arrays are avoided.
+#
+#       The "traditional" practice of packing multiple parameters into a
+#       space-separated string is a well documented source of bugs and security
+#       problems, so this is (mostly) avoided, by progressively accumulating
+#       options in "$@", and eventually passing that to Java.
+#
+#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
+#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
+#       see the in-line comments for details.
+#
+#       There are tweaks for specific operating systems such as AIX, CygWin,
+#       Darwin, MinGW, and NonStop.
+#
+#   (3) This script is generated from the Groovy template
+#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
+#       within the Gradle project.
+#
+#       You can find Gradle at https://github.com/gradle/gradle/.
 #
 ##############################################################################
 
 # Attempt to set APP_HOME
+
 # Resolve links: $0 may be a link
-PRG="$0"
-# Need this for relative symlinks.
-while [ -h "$PRG" ] ; do
-    ls -ld "$PRG"
-    link=`expr "$PRG" : '.*-> \(.*\)$'`
-    if expr "$link" : '/.*' > /dev/null; then
-        PRG="$link"
-    else
-        PRG=`dirname "$PRG"`"/$link"
-    fi
+app_path=$0
+
+# Need this for daisy-chained symlinks.
+while
+    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
+    [ -h "$app_path" ]
+do
+    ls=$( ls -ld "$app_path" )
+    link=${ls#*' -> '}
+    case $link in             #(
+      /*)   app_path=$link ;; #(
+      *)    app_path=$APP_HOME$link ;;
+    esac
 done
-SAVED="`pwd`"
-cd "`dirname \"$PRG\"`/" >/dev/null
-APP_HOME="`pwd -P`"
-cd "$SAVED" >/dev/null
 
-APP_NAME="Gradle"
-APP_BASE_NAME=`basename "$0"`
+# This is normally unused
+# shellcheck disable=SC2034
+APP_BASE_NAME=${0##*/}
+# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
+APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit
 
-# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
+# Use the maximum available, or set MAX_FD != -1 to use that value.
+MAX_FD=maximum
 
-# Use the maximum available, or set MAX_FD != "max" to use that value.
-MAX_FD="maximum"
+warn () {
+    echo "$*"
+} >&2
 
-warn ( ) {
-    echo "$*" >&2
-}
-
-die ( ) {
+die () {
     echo
     echo "$*"
     echo
     exit 1
-}
+} >&2
 
 # OS specific support (must be 'true' or 'false').
 cygwin=false
 msys=false
-pw32=false
-nwjs=false
 darwin=false
 nonstop=false
-case "`uname`" in
-  CYGWIN* )
-    cygwin=true
-    ;;
-  Darwin* )
-    darwin=true
-    ;;
-  MSYS* | MINGW* )
-    msys=true
-    ;;
-  NWJS )
-    nwjs=true
-    ;;
-  SunOS )
-    nonstop=true
-    ;;
+case "$( uname )" in                #(
+  CYGWIN* )         cygwin=true  ;; #(
+  Darwin* )         darwin=true  ;; #(
+  MSYS* | MINGW* )  msys=true    ;; #(
+  NONSTOP* )        nonstop=true ;;
 esac
 
 CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
@@ -99,11 +117,11 @@ CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
 
 # Determine the Java command to use to start the JVM.
 if [ -n "$JAVA_HOME" ] ; then
-    if [ -x "$JAVA_HOME/jre/bin/java" ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
         # IBM's JDK on AIX uses strange locations for the executables
-        JAVACMD="$JAVA_HOME/jre/bin/java"
+        JAVACMD=$JAVA_HOME/jre/sh/java
     else
-        JAVACMD="$JAVA_HOME/bin/java"
+        JAVACMD=$JAVA_HOME/bin/java
     fi
     if [ ! -x "$JAVACMD" ] ; then
         die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
@@ -112,7 +130,7 @@ Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
     fi
 else
-    JAVACMD="java"
+    JAVACMD=java
     if ! command -v java >/dev/null 2>&1
     then
         die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
@@ -123,21 +141,20 @@ location of your Java installation."
 fi
 
 # Increase the maximum file descriptors if we can.
-if ! "$cygwin" && ! "$darwin" && ! "$nwjs" ; then
+if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
     case $MAX_FD in #(
       max*)
         # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
-        # shellcheck disable=SC3045
+        # shellcheck disable=SC2039,SC3045
         MAX_FD=$( ulimit -H -n ) ||
             warn "Could not query maximum file descriptor limit"
     esac
     case $MAX_FD in  #(
       '' | soft) :;; #(
       *)
-        # In POSIX sh, ulimit -n may round down to even higher values,
-        # so add some 5% more to round up the default limit
-        # shellcheck disable=SC3045
-        ulimit -n "$((MAX_FD + MAX_FD / 20))" ||
+        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
+        # shellcheck disable=SC2039,SC3045
+        ulimit -n "$MAX_FD" ||
             warn "Could not set maximum file descriptor limit to $MAX_FD"
     esac
 fi
@@ -146,63 +163,50 @@ fi
 #   * args from the command line
 #   * the main class name
 #   * -classpath
-#   * -D...sysproperties
+#   * -D...appname settings
 #   * --module-path (only if needed)
 #   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.
 
 # For Cygwin or MSYS, switch paths to Windows format before running java
 if "$cygwin" || "$msys" ; then
-    APP_HOME=$( cygwin_path "$APP_HOME" )
-    CLASSPATH=$( cygwin_path "$CLASSPATH" )
+    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
+    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
 
-    JAVACMD=$( cygwin_path "$JAVACMD" )
+    JAVACMD=$( cygpath --unix "$JAVACMD" )
 
-    # We build the pattern for arguments to be converted via cygpath
-    ROOTDIRSRAW=$( find -L / -maxdepth 3 -type d -name java >/dev/null 2>&1 && find -L / -maxdepth 3 -type d -name java | head -1 )
-    # Add a user-defined pattern to the cygpath arguments
-    if [ "$GRADLE_CYGWIN_HOME" != "" ] ; then
-        ROOTDIRS="$ROOTDIRS $GRADLE_CYGWIN_HOME"
-    fi
     # Now convert the arguments - kludge to limit ourselves to /bin/sh
-    i=0
-    for arg in "$@" ; do
-        CHECK=`echo "$arg"|awk '{print substr($0,1,1)}'`
-        CHECK2=`echo "$arg"|awk '{print substr($0,1,2)}'`
-        if [ "$CHECK" = "-" ] || [ "$CHECK2" = "--" ] ; then                    # Looks like an option
-            ARGS="$ARGS \"$arg\""
-            continue
+    for arg do
+        if
+            case $arg in                                #(
+              -*)   false ;;                            # don't mess with options #(
+              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
+                    [ -e "$t" ] ;;                      #(
+              *)    false ;;
+            esac
+        then
+            arg=$( cygpath --path --ignore --mixed "$arg" )
         fi
-        if [ "$arg" != '' ] ; then
-            ARGS="$ARGS \"$( cygwin_path "$arg" )\""
-        fi
-        i=$((i+1))
+        # Roll the args list around exactly as many times as the number of
+        # args, so each arg winds up back in the position where it started, but
+        # possibly modified.
+        #
+        # NB: a `for` loop captures its iteration list before it begins, so
+        # changing the positional parameters here affects neither the number of
+        # iterations, nor the values presented in `arg`.
+        shift                   # remove old arg
+        set -- "$@" "$arg"      # push replacement arg
     done
-    case $i in
-        (0) set -- ;;
-        (1) set -- "$ARGS0" ;;
-        (2) set -- "$ARGS0" "$ARGS1" ;;
-        (3) set -- "$ARGS0" "$ARGS1" "$ARGS2" ;;
-        (4) set -- "$ARGS0" "$ARGS1" "$ARGS2" "$ARGS3" ;;
-        (5) set -- "$ARGS0" "$ARGS1" "$ARGS2" "$ARGS3" "$ARGS4" ;;
-        (6) set -- "$ARGS0" "$ARGS1" "$ARGS2" "$ARGS3" "$ARGS4" "$ARGS5" ;;
-        (7) set -- "$ARGS0" "$ARGS1" "$ARGS2" "$ARGS3" "$ARGS4" "$ARGS5" "$ARGS6" ;;
-        (8) set -- "$ARGS0" "$ARGS1" "$ARGS2" "$ARGS3" "$ARGS4" "$ARGS5" "$ARGS6" "$ARGS7" ;;
-        (9) set -- "$ARGS0" "$ARGS1" "$ARGS2" "$ARGS3" "$ARGS4" "$ARGS5" "$ARGS6" "$ARGS7" "$ARGS8" ;;
-    esac
 fi
 
-# Escape application args
-save ( ) {
-    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
-    echo " "
-}
-APP_ARGS=$( save "$@" )
 
-# Collect all arguments for the java command;
-#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
-#     shell script including quotes and variable substitutions, so put them in
-#     double quotes to make sure that they get re-expanded; and
-#   * put everything else in single quotes, so that the shell interprets it literally.
+# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
+DEFAULT_JVM_OPTS='-Dfile.encoding=UTF-8 "-Xmx64m" "-Xms64m"'
+
+# Collect all arguments for the java command:
+#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
+#     and any embedded shellness will be escaped.
+#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable and will be
+#     treated as '${Hostname}' itself on the command line.
 
 set -- \
         "-Dorg.gradle.appname=$APP_BASE_NAME" \
@@ -218,51 +222,28 @@ fi
 
 # Use "xargs" to parse quoted args.
 #
-# With -n1 it outputs one arg per line, when -0 it outputs character per line
-# of the form '\n'; this also takes care of the case of last arg in a series
-# which doesn't end with \n; the string coming into next iteration has no '\n'
-# at all; the last iteration fishes the last byte out of the input (the '-c')
-# to make sure we only use up the prefix which ends at the last complete arg
+# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
 #
-# Usage within the cycle '| xargs -I {} sh -c "{}' would then use the result
-# of the substitution, but better quote vars that can have backslashes, meaning
-# that would be the opposite of using it for processing $AF_JAVA_OPTS
-# and the first fragment of $JAVA_OPTS with quotes.
-rest=
-for arg in "$@" ; do
-    if [ -n "$rest" ] ; then
-        arg="$arg"
-    fi
-    case "$arg" in
-        *\'*) arg="'"'"'"'"'"'"'"'"'"'"$arg"'"'"'"'"'"'"'"'"'"' ;;
-    esac
-    rest="$rest $arg"
-done
-# by using the pattern, we are escaping everything, including the $s.
+# In Bash we could simply go:
 #
-# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
+#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
+#   set -- "${ARGS[@]}" "$@"
+#
+# but POSIX shell has neither arrays nor command substitution, so instead we
+# post-process each arg (as a line of input to sed) to backslash-escape any
+# character that might be a shell metacharacter, then use eval to reverse
+# that process (while maintaining the separation between arguments), and wrap
+# the whole thing up as a single "set" statement.
+#
+# This will of course break if any of these variables contains a newline or
+# an unmatched quote.
+#
 
-# Regular expression matching bash/sh style comments
-COMMENT_PATTERN="^[[:space:]]*#"
-
-# While IFS read is supported in both sh and bash, the behavior differs when the input has trailing whitespace:
-# bash will not strip the trailing whitespace (as per POSIX), but sh will strip it (in all versions of sh that we've tested)
-# This test creates a shell script containing actual backslash escape characters, which are also variable-expanded
-# This allows us to verify the shell behavior and execute exactly what we need
-SCRIPT='
-if [ -n "@input@" ] ; then
-  printf '%s\n' "@input@"
-  exit 1
-fi
-'
-SCRIPT_OUT=$(set -- '\\'; sh -c "$SCRIPT" -- "$@" 2>&1)
-if [ ! "x$SCRIPT_OUT" = "x" ] ; then
-  echo "ERROR: @input@ argument was not clean (may have trailing whitespace)."
-  exit 1
-fi
-
-# Use eval to re-quote arguments in a way that makes them usable in a shell again:
-eval "set -- $rest"
+eval "set -- $(
+        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
+        xargs -n1 |
+        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
+        tr '\n' ' '
+    )" '"$@"'
 
 exec "$JAVACMD" "$@"
